---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3166188320-bGENiFK2SCkJqJrnoEoczUImx95umOkRcvDtLRP
:access_token_secret: EAUTjeUTkcq025jsaVBSU2mZb4GUEJXucJ3N4yYsvLzuX
